global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape Node Exporter metrics
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  # Scrape Jenkins metrics
  - job_name: "jenkins"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
